Repository brevia-ai/brevia-app, pull requests merged in 2025-06, with the labels that each got.

#50 Dependabot configuration
  .github/dependabot.yml
Labels: enhancement

#48 Add minimum Brevia API version check
  components/Dialog/SystemInfo.vue
  components/Main/Footer.vue
  locales/en/messages.json
  locales/it/messages.json
  middleware/auth.global.ts
  nuxt.config.ts
  package-lock.json
  package.json
  server/api/brevia/versions.get.ts
  server/utils/versions.ts
  store/states.ts
Labels: release:patch

#47 New Conversation page
  components/Dashboard/Menu.vue
  locales/en/messages.json
  locales/it/messages.json
  nuxt.config.ts
  pages/conversation.vue
Labels: release:minor
