Repository brevia-ai/brevia-app, pull requests merged in 2025-01, with the labels that each got.

#34 Handle Brevia general settings
  components/AppModal.vue
  components/Dialog/ResetConfig.vue
  components/Main/Header.vue
  locales/en/messages.json
  locales/it/messages.json
  pages/general-config.vue
  server/api/brevia/config.get.ts
  server/api/brevia/config.post.ts
  server/api/brevia/config/reset.post.ts
  server/api/brevia/config/schema.get.ts
  store/modal.ts
Labels: release:minor

#37 Use `H3Event` in `useRuntimeConfig`
  middleware/auth.global.ts
  modules/bedita/runtime/server/api/bedita/auth/user.patch.ts
  package-lock.json
  package.json
  server/api/brevia/[...slug].get.ts
  server/api/brevia/[...slug].post.ts
  server/api/brevia/auth/login.post.ts
  server/api/brevia/auth/logout.post.ts
  server/api/brevia/chat.post.ts
  server/api/brevia/config.get.ts
  server/api/brevia/config.post.ts
  server/api/brevia/config/reset.post.ts
  server/api/brevia/config/schema.get.ts
  server/api/brevia/index/upload.post.ts
  server/api/brevia/transcribe.post.ts
  server/api/brevia/upload_analyze.post.ts
  server/api/brevia/upload_summarize.post.ts
  server/api/brevia/versions.get.ts
  server/api/projects.get.ts
  server/utils/api-client.ts
  server/utils/project.ts
  server/utils/session.ts
Labels: release:patch

#38 Show Share info to non admin users
  components/Element/ChatbotShare.vue
  locales/en/messages.json
  locales/it/messages.json
  pages/chatbot/edit-[id].vue
Labels: release:patch

#36 Custom Error page
  error.vue
  pages/chatbot-iframe/[uuid].vue
  public/brevia-logo-shatter.png
Labels: enhancement

#30 Handle `date-time` and plain `string` types in metadata
  components/Dialog/EditMetadata.vue
Labels: release:patch
